### ISSUE TITLE
Error message "RESTEASY004655: Unable to invoke request"

### ISSUE THREAD

**Issue by webwurst** [kiwigrid/keycloak-client-controller#9]
I am getting that error message. My `keycloaks.k8s.kiwigrid.com` looks like this:

```yaml
apiVersion: k8s.kiwigrid.com/v1beta1
kind: Keycloak
metadata:
  name: keycloak-test1
spec:
  clientId: admin-cli
  passwordSecretKey: password
  passwordSecretName: keycloak-http
  passwordSecretNamespace: keycloak-test1
  realm: master
  url: https://keycloak-test1.mydomain.org/auth
  username: admin
```
The secret also exists and was created this way
```bash
kubectl create secret generic keycloak-http \
  --from-literal=password=$(openssl rand -base64 32 | tr -d "\n" | base64)
```

What can I do to debug this further?
